---
# Tasks only to be exectuted on a host running a gplazma cell

- name: install gplazma.conf
  tags: conf
  template:
    src: gplazma.conf.j2
    dest: /etc/dcache/gplazma.conf
    backup: yes
    owner: root
    group: root
    mode: 0644

- name: install grid-mapfile
  template:
    src: grid-mapfile.j2
    dest: /etc/grid-security/grid-mapfile
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: dcache_grid_mapfile is defined

- name: install grid-vorolemap
  tags: conf
  template:
    src: grid-vorolemap.j2
    dest: /etc/grid-security/grid-vorolemap
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: dcache_vorolemap is defined
    
- name: install storage-authzdb
  tags: conf
  template:
    src: storage-authzdb.j2
    dest: /etc/grid-security/storage-authzdb
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: dcache_authzdb is defined

- name: install dcache.kpwd
  template:
    src: dcache.kpwd.j2
    dest: /etc/dcache/dcache.kpwd
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: dcache_kpwd is defined
  
