- name: get list of pool paths from layout file
  shell:
    cmd: "sed  -n 's/^pool.path=//p' /etc/dcache/layouts/{{ inventory_hostname | regex_replace('([^\\.]+).*', '\\1') }}.conf"
    warn: no
  register: outp_pool_list
  changed_when: False

- name: create pool directories for pools found in layout file
  file:
    state: directory
    path: '{{ item }}'
    owner: dcache
    group: dcache
    mode: 0755
  loop: '{{ outp_pool_list.stdout.split() }}'

- name: create data dir within pool directories
  file:
    state: directory
    path: '{{ item }}/data'
    owner: dcache
    group: dcache
    mode: 0755
  loop: '{{ outp_pool_list.stdout.split() }}'
  
